"""Initial migration

Revision ID: 79cf1e53acd4
Revises: 
Create Date: 2025-05-24 19:09:40.057012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cf1e53acd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_penerima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('k1', sa.Integer(), nullable=False),
    sa.Column('k2', sa.Integer(), nullable=False),
    sa.Column('k3', sa.Integer(), nullable=False),
    sa.Column('k4', sa.Integer(), nullable=False),
    sa.Column('k5', sa.Integer(), nullable=False),
    sa.Column('k6', sa.Integer(), nullable=False),
    sa.Column('k7', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_penerima')
    # ### end Alembic commands ###
